### ISSUE TITLE
Permission denied in subprocess

### ISSUE THREAD

**Issue by nildan** [zdenulo/google-cloud-functions-system-packages#1]
Thanks for a great article and examples!

I have cloned the repo and deployed cf_ascii to GCF, but I get an error when calling the function:

> Traceback (most recent call last):
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 346, in run_http_function
>     result = _function_handler.invoke_user_function(flask.request)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 217, in invoke_user_function
>     return call_user_function(request_or_event)
>   File "/env/local/lib/python3.7/site-packages/google/cloud/functions/worker.py", line 210, in call_user_function
>     return self._user_function(request_or_event)
>   File "/user_code/main.py", line 15, in main
>     p = subprocess.Popen(cmd, stderr=subprocess.PIPE, stdout=subprocess.PIPE)
>   File "/opt/python3.7/lib/python3.7/subprocess.py", line 775, in __init__
>     restore_signals, start_new_session)
>   File "/opt/python3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> **PermissionError: [Errno 13] Permission denied: './figlet'**

Seems like subprocess cannot access figlet. Am I missing something?

**Comment by zdenulo** [comment]
I would try to change the permissions of figlet binary to 777 and then upload code again and try. Nothing else comes to my mind.

**Comment by nildan** [comment]
Correct, thanks @zdenulo! That seems to imply that the function cannot be deployed from Windows, see https://stackoverflow.com/questions/60383631/how-to-solve-file-permissions-error-with-subprocess-in-cloud-functions/
